### ISSUE TITLE
Close the form by clicking outside of it

### ISSUE THREAD

**Issue by olpeh** [futurice/hours-ui-cycle#11]
Situation:
- Focus the input form for a day but don't click save or cancel
- Scroll forward or backward in time
- Try to click a day -> nothing happens because the form is still open for another day out of the sight

**Comment by phadej** [comment]
The point of editing single day at time, is that you *do* click *save* or *cancel*.

I'm :-1: about closing the form by clicking outside it, as unfortunate missclick will get my angry as **iff** the data entered is lost. It would be probably ok, if re-opening the form on that day will have the information preserved.

**Comment by olpeh** [comment]
Yes, it could be a missclick too. 
But this happens to me quite often that I start adding hours for today but then I remember I was suppossed to edit/add for another day and then scroll to that day but then it's impossible to add/edit without going back and clicking save or cancel.

**Comment by janivihervas** [comment]
This to me sounds like the same as this issue: [https://github.com/futurice/hours-ui-cycle/issues/13](https://github.com/futurice/hours-ui-cycle/issues/13). Currently it is possible to edit multiple days at the same time, but one has to click cancel or save. Closing the form by clicking outside of the box conflicts with editing multiple days, as it would close all of the open forms. Is this ok, @olpeh?

**Comment by olpeh** [comment]
Sounds good @janivihervas
