### ISSUE TITLE
Possibility to mark more than 12 hours / day

### ISSUE THREAD

**Issue by chlif** [futurice/hours-ui-cycle#12]
I know this is a niche feature (hopefully!) but sometimes the work days prolong because of an event to last longer than 12 hours. It would be nice to be able to mark that with Futuhours.

**Comment by phadej** [comment]
Is it possible to have a single hour marking over 12 hours in planmill?

**Comment by chlif** [comment]
Yes. At least through the UI you can do that.

**Comment by janivihervas** [comment]
Implemented here: https://github.com/futurice/hours-ui-cycle/blob/d6cb0b942efb61726985be95d15c938fac2ffad5/src/components/Entry/EntryEdit.js#L122-L123. Current options are 0.5 h ... 18 hours. I'll implement correct error handling for it later as currently one can mark more than 24 hours per day.
