### ISSUE TITLE
Holidays that respect PlanMill Capacity Calendar

### ISSUE THREAD

**Issue by mixman** [futurice/hours-ui-cycle#14]
Employees are assigned a capacity calendar, that includes the holidays for that country/region. While Finland has a single set of Holidays, in Germany this is region-specific (eg. Berlin and Munchen do not share all the same holidays).

On futuhours it should be visible which days are holidays.

**Comment by janivihervas** [comment]
Frontend implemented, holiday data comes from the backend:

![screen shot 2016-08-02 at 8 14 17](https://cloud.githubusercontent.com/assets/6649492/17317714/43148522-5889-11e6-9f75-c2a48193cc68.png)
