### ISSUE TITLE
Be able to mark part/half day for absences (e.g. half day sick leave)

### ISSUE THREAD

**Issue by FeiKong** [futurice/hours-ui-cycle#4]

**Comment by phadej** [comment]
You can do it in Planmill, so it should be possible to do in Futuhours as well.

**Comment by janivihervas** [comment]
Implemented:
![screen shot 2016-08-04 at 10 17 05](https://cloud.githubusercontent.com/assets/6649492/17393511/b9c22a40-5a2c-11e6-9267-c097cf34f4b6.png)

Error handling:
![screen shot 2016-08-04 at 10 17 25](https://cloud.githubusercontent.com/assets/6649492/17393518/c43e71b8-5a2c-11e6-9904-ab4e876923c1.png)

**Comment by FeiKong** [comment]
Thanks a lot, Jani!
:)
