### ISSUE TITLE
Bug: unsaved changes gets disappeared

### ISSUE THREAD

**Issue by hakaotu** [futurice/hours-ui-cycle#5]
bug in the current version: you enter the data and click save. Something goes wrong and the markings are not saved --> you need to enter the data again

**Comment by phadej** [comment]
Related to: https://github.com/futurice/hours-ui-cycle/issues/13

**Comment by janivihervas** [comment]
Implemented: https://github.com/futurice/hours-ui-cycle/blob/cd0ddd68c768b95a5cff6051d8faba4176029731/src/reducers/hours.js#L610-L691
Tests: https://github.com/futurice/hours-ui-cycle/blob/cd0ddd68c768b95a5cff6051d8faba4176029731/src/reducers/__specs__/day.spec.js#L944-L1943

TL;DR: Every entry in day is saved separately based on API results. If a request fails, it stays in the edit state and is only deleted if user cancels the editing.

Example:
```
saved state
  - entries
edit state
  - entries
    - 1
    - 2
    - 3

SAVE ==>
responses:
entries
  - 1 ok
  - 2 fail
  - 3 ok

==>
saved state
  - entries
    - 1
    - 3
edit state
  - entries
    - 1
    - 2
    - 3
```
