### ISSUE TITLE
pre-filled hour markings for those who work 7.5h (or 8h) per day for the same project

### ISSUE THREAD

**Issue by hakaotu** [futurice/hours-ui-cycle#6]
When system notices that you mark the almost same hours for the same project it would start suggesting you the same project and hours prefilled still allowing you to adjust the hours

**Comment by phadej** [comment]
related to https://github.com/futurice/hours-ui-cycle/issues/8

**Comment by phadej** [comment]
*EDIT* hours ui does currently this as well, but we should make it even better (for people with multiple concurrent projects).

**Comment by janivihervas** [comment]
Implemented:

![screen shot 2016-08-10 at 10 55 30](https://cloud.githubusercontent.com/assets/6649492/17546176/81ac1cbc-5ee9-11e6-8758-d1903fdb83cd.png)

Logic: 
Task list in project is sorted based on most recent usage by backend, each task holds `latestEntry` field with information about the latest entry. If the latest entry has the latest hours, ui uses that as starting value for a new entry. Else the new entry's hours is `max(0.5, defaultWorkHours - sum(day.entries.map(_.hours)))`.
New entry's project is the next most recently used project, which isn't used in other entries in the day.

Works for people with mostly one entry per day to the same project, or for people with multiple projects with same hours per day, e.g. 2.5 hours to project 1 and 5.0 hours to project 2 per day.

Backend can handle more complex logic, like if a user marks full day to a single project and on Fridays marks one hour to internal stuff and the rest on the same project.
