### ISSUE TITLE
Possibility to add hours for multiple days at once

### ISSUE THREAD

**Issue by hakaotu** [futurice/hours-ui-cycle#7]
e.g. I have worked the whole week for the same project. I would be able to mark the whole week at once say from the 4th of July until 8th july into the same project and with the same hours

**Comment by phadej** [comment]
I guess that we'd prefer people to mark hours *daily*. 

Thus: 
- re-entering information should be quick (see https://github.com/futurice/hours-ui-cycle/issues/10)
- making entering multiple days should be possible, i.e. you can start entering the next day, when the previous is still saving (current ui blocks - and that's annoying part?)

**Comment by janivihervas** [comment]
I would avoid too much complexity to ensure easy usage. Currently editing multiple days at once is possible, and you can mark full day hours with the most recent information with two clicks (click to edit day, information is pre-filled, click save).
